name: gh actions demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 13ruceYu/lego-backend
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: node -v
      - run: npm i -g typescript
      - run: tsc -v