name: test secret
on: [push]
jobs:
  secret-ssh-action:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script_stop: true
          script: |
            pwd
            ls -l
            touch gh-secret.txt
            echo ${{ secrets.TEST_TXT }} >> gh-secret.txt